rows = 3
cols = 110

for i in range(rows):
    for j in range(cols):
        if i == 0:
            if j <= 2:
                print("*", end="")
            elif j <= 7:
                print("#", end="")
            elif j <= 9:
                print("%", end="")
            elif j <= 12:
                print("#", end="")
            elif j <= 22:
                print("@", end="")
            elif j == 23:
                print("%", end="")
            elif j == 24:
                print("#", end="")
            elif j == 25:
                print("*", end="")
            elif j <= 27:
                print("=", end="")
            elif j <= 30:
                print("+", end="")
            elif j == 31:
                print("*", end="")
            elif j <= 35:
                print("#", end="")
            elif j <= 37:
                print("+", end="")
            elif j == 38:
                print("=", end="")
            elif j <= 53:
                print("-", end="")
            elif j <= 57:
                print("=", end="")
            elif j <= 66:
                print("-", end="")
            elif j == 67:
                print("=", end="")
            elif j <= 69:
                print("+", end="")
            elif j <= 72:
                print("=", end="")
            elif j == 73:
                print("-", end="")
            elif j == 74:
                print(":", end="")
            elif j == 75:
                print("+", end="")
            elif j <= 79:
                print("#", end="")
            elif j <= 81:
                print("%", end="")
            elif j <= 83:
                print("#", end="")
            elif j <= 97:
                print("%", end="")
            else:
                print("#", end="")

        # ================= LINE 2 =================
        elif i == 1:
            if j <= 2:
                print("*", end="")
            elif j <= 5:
                print("#", end="")
            elif j <= 8:
                print("%", end="")
            elif j == 9:
                print("#", end="")
            elif j <= 18:
                print("@", end="")
            elif j == 19:
                print("%", end="")
            elif j == 20:
                print("*", end="")
            elif j == 21:
                print("=", end="")
            elif j == 22:
                print("-", end="")
            elif j == 23:
                print(":", end="")
            elif j <= 28:
                print(".", end="")
            elif j <= 32:
                print(":", end="")
            elif j <= 35:
                print("-", end="")
            elif j <= 38:
                print(":", end="")
            elif j <= 41:
                print("-", end="")
            elif j <= 44:
                print(":", end="")
            elif j <= 47:
                print("-", end="")
            elif j <= 50:
                print("=", end="")
            elif j <= 55:
                print("+", end="")
            elif j <= 58:
                print("=", end="")
            elif j <= 60:
                print("+", end="")
            elif j == 61:
                print("*", end="")
            elif j == 62:
                print("=", end="")
            elif j <= 66:
                print("+", end="")
            elif j == 67:
                print("*", end="")
            elif j == 68:
                print("+", end="")
            elif j == 69:
                print("-", end="")
            elif j == 70:
                print(":", end="")
            elif j == 71:
                print("=", end="")
            elif j <= 78:
                print("#", end="")
            elif j <= 92:
                print("%", end="")
            else:
                print("#", end="")

        # ================= LINE 3 =================
        elif i == 2:
            if j <= 2:
                print("*", end="")
            elif j <= 5:
                print("#", end="")
            elif j <= 8:
                print("%", end="")
            elif j == 9:
                print("#", end="")
            elif j <= 15:
                print("@", end="")
            elif j == 16:
                print("%", end="")
            elif j == 17:
                print("*", end="")
            elif j == 18:
                print("=", end="")
            elif j == 19:
                print("-", end="")
            elif j <= 23:
                print(":", end="")
            elif j <= 29:
                print(".", end="")
            elif j <= 41:
                print(":", end="")
            elif j == 42:
                print("-", end="")
            elif j <= 48:
                print(":", end="")
            elif j == 49:
                print("-", end="")
            elif j <= 51:
                print("=", end="")
            elif j <= 54:
                print("+", end="")
            elif j == 55:
                print("=", end="")
            elif j <= 57:
                print("+", end="")
            elif j == 58:
                print("*", end="")
            elif j <= 60:
                print("#", end="")
            elif j <= 63:
                print("*", end="")
            elif j <= 65:
                print("#", end="")
            elif j == 66:
                print("*", end="")
            elif j == 67:
                print("=", end="")
            elif j <= 74:
                print("#", end="")
            elif j <= 88:
                print("%", end="")
            else:
                print("#", end="")

    print()
rows = 5
cols = 110

for i in range(rows):
    for j in range(cols):

        # ========= LINE 1 =========
        if i == 0:
            if j <= 2:
                print("*", end="")
            elif j <= 5:
                print("#", end="")
            elif j <= 10:
                print("%", end="")
            elif j <= 13:
                print("@", end="")
            elif j == 14:
                print("%", end="")
            elif j == 15:
                print("#", end="")
            elif j == 16:
                print("*", end="")
            elif j <= 18:
                print("-", end="")
            elif j <= 25:
                print(":", end="")
            elif j <= 28:
                print(".", end="")
            elif j <= 50:
                print(":", end="")
            elif j == 51:
                print("-", end="")
            elif j <= 53:
                print("=", end="")
            elif j == 54:
                print("+", end="")
            elif j <= 56:
                print("=", end="")
            elif j <= 62:
                print("-", end="")
            elif j <= 64:
                print("=", end="")
            elif j == 65:
                print("+", end="")
            elif j <= 68:
                print("#", end="")
            elif j == 69:
                print("*", end="")
            elif j == 70:
                print("%", end="")
            elif j == 71:
                print("#", end="")
            elif j == 72:
                print("*", end="")
            elif j == 73:
                print("#", end="")
            elif j == 74:
                print("*", end="")
            elif j == 75:
                print("=", end="")
            elif j == 76:
                print("-", end="")
            elif j == 77:
                print("=", end="")
            elif j <= 81:
                print("#", end="")
            elif j <= 97:
                print("%", end="")
            else:
                print("#", end="")
                
        elif i == 1:
            if j <= 2:
                print("*", end="")
            elif j <= 5:
                print("#", end="")
            elif j <= 10:
                print("%", end="")
            elif j <= 12:
                print("@", end="")
            elif j == 13:
                print("%", end="")
            elif j == 14:
                print("#", end="")
            elif j == 15:
                print("+", end="")
            elif j <= 19:
                print("-", end="")
            elif j <= 27:
                print(":", end="")
            elif j <= 31:
                print(".", end="")
            elif j <= 33:
                print(":", end="")
            elif j <= 37:
                print(".", end="")
            elif j <= 49:
                print(":", end="")
            elif j <= 51:
                print("-", end="")
            elif j <= 53:
                print("=", end="")
            elif j <= 56:
                print("-", end="")
            elif j <= 63:
                print(":", end="")
            elif j <= 65:
                print("-", end="")
            elif j <= 67:
                print("=", end="")
            elif j == 68:
                print("+", end="")
            elif j == 69:
                print("*", end="")
            elif j == 70:
                print("#", end="")
            elif j == 71:
                print("%", end="")
            elif j == 72:
                print("#", end="")
            elif j <= 74:
                print("*", end="")
            elif j == 75:
                print("+", end="")
            elif j <= 77:
                print("-", end="")
            elif j == 78:
                print("*", end="")
            elif j <= 90:
                print("%", end="")
            else:
                print("#", end="")

        elif i == 2:
            if j <= 2: print("*", end="")
            elif j <= 5:
                print("#", end="")
            elif j <= 9:
                print("%", end="")
            elif j <= 12:
                print("@", end="")
            elif j == 13:
                print("#", end="")
            elif j == 14:
                print("%", end="")
            elif j <= 17:
                print("+", end="")
            elif j <= 20:
                print("-", end="")
            elif j == 21:
                print(":", end="")
            elif j <= 24:
                print("-", end="")
            elif j <= 27:
                print(":", end="")
            elif j <= 37:
                print(".", end="")
            elif j <= 44:
                print(":", end="")
            elif j <= 47:
                print("-", end="")
            elif j <= 51:
                print("=", end="")
            elif j <= 55:
                print("+", end="")
            elif j == 56:
                print("=", end="")
            elif j <= 61:
                print("-", end="")
            elif j <= 66:
                print(":", end="")
            elif j <= 69:
                print("-", end="")
            elif j == 70:
                print("=", end="")
            elif j == 71:
                print("+", end="")
            elif j <= 73:
                print("#", end="")
            elif j <= 75:
                print("%", end="")
            elif j <= 79:
                print("#", end="")
            elif j == 80:
                print("*", end="")
            elif j == 81:
                print("=", end="")
            elif j <= 83:
                print("-", end="")
            elif j <= 98:
                print("%", end="")
            else:
                print("#", end="")

        elif i == 3:
            if j <= 2: print("*", end="")
            elif j <= 5: print("#", end="")
            elif j <= 9: print("%", end="")
            elif j <= 12: print("@", end="")
            elif j <= 14: print("%", end="")
            elif j <= 16: print("*", end="")
            elif j <= 19: print("+", end="")
            elif j <= 21: print("=", end="")
            elif j <= 24: print("-", end="")
            elif j <= 28: print(":", end="")
            elif j <= 33: print(".", end="")
            elif j <= 43: print(":", end="")
            elif j == 44: print("-", end="")
            elif j == 45: print("=", end="")
            elif j == 46: print("-", end="")
            elif j == 47: print("=", end="")
            elif j <= 49: print("+", end="")
            elif j == 50: print("*", end="")
            elif j <= 52: print("%", end="")
            elif j == 53: print("#", end="")
            elif j == 54: print("+", end="")
            elif j <= 56: print("-", end="")
            elif j <= 60: print("=", end="")
            elif j <= 62: print("-", end="")
            elif j <= 64: print(":", end="")
            elif j == 65: print("-", end="")
            elif j == 66: print("=", end="")
            elif j == 67: print("*", end="")
            elif j <= 69: print("%", end="")
            elif j == 70: print("#", end="")
            elif j <= 85: print("%", end="")
            else: print("#", end="")

        # ========= LINE 5 =========
        elif i == 4:
            if j <= 3: print("*", end="")
            elif j <= 7: print("#", end="")
            elif j <= 10: print("%", end="")
            elif j <= 13: print("@", end="")
            elif j == 14: print("%", end="")
            elif j == 15: print("#", end="")
            elif j <= 17: print("*", end="")
            elif j <= 20: print("+", end="")
            elif j <= 22: print("=", end="")
            elif j <= 25: print("-", end="")
            elif j <= 27: print(":", end="")
            elif j <= 34: print(".", end="")
            elif j <= 37: print(":", end="")
            elif j <= 40: print("-", end="")
            elif j == 41: print("=", end="")
            elif j <= 43: print(":", end="")
            elif j == 44: print("-", end="")
            elif j == 45: print("+", end="")
            elif j == 46: print("*", end="")
            elif j == 47: print("+", end="")
            elif j == 48: print("#", end="")
            elif j == 49: print("%", end="")
            elif j == 50: print("@", end="")
            elif j == 51: print("#", end="")
            elif j <= 54: print("-", end="")
            elif j <= 56: print("=", end="")
            elif j <= 59: print("+", end="")
            elif j == 60: print("*", end="")
            elif j == 61: print("+", end="")
            elif j == 62: print("=", end="")
            elif j <= 64: print("-", end="")
            elif j <= 66: print(":", end="")
            elif j == 67: print("=", end="")
            elif j <= 69: print("*", end="")
            elif j == 70: print("=", end="")
            elif j == 71: print("+", end="")
            elif j == 72: print("*", end="")
            elif j == 73: print("=", end="")
            elif j == 74: print(":", end="")
            elif j == 75: print("-", end="")
            elif j == 76: print("#", end="")
            elif j <= 86: print("%", end="")
            else: print("#", end="")

    print()
rows = 5
cols = 110

for i in range(rows):
    for j in range(cols):

        # ========= LINE 1 =========
        if i == 0:
            if j <= 4: print("*", end="")
            elif j <= 8: print("#", end="")
            elif j == 9: print("%", end="")
            elif j == 10: print("#", end="")
            elif j <= 13: print("@", end="")
            elif j == 14: print("%", end="")
            elif j <= 19: print("*", end="")
            elif j <= 21: print("+", end="")
            elif j <= 23: print("=", end="")
            elif j <= 25: print("-", end="")
            elif j <= 27: print(":", end="")
            elif j <= 32: print(".", end="")
            elif j == 33: print(":", end="")
            elif j <= 35: print("=", end="")
            elif j == 36: print("+", end="")
            elif j <= 38: print("*", end="")
            elif j <= 41: print("+", end="")
            elif j <= 43: print("=", end="")
            elif j <= 45: print(".", end="")
            elif j == 46: print(":", end="")
            elif j == 47: print("-", end="")
            elif j == 48: print("*", end="")
            elif j == 49: print("%", end="")
            elif j <= 51: print("@", end="")
            elif j == 52: print("#", end="")
            elif j == 53: print("=", end="")
            elif j <= 57: print("#", end="")
            elif j <= 62: print("@", end="")
            elif j == 63: print("%", end="")
            elif j == 64: print("#", end="")
            elif j <= 66: print("-", end="")
            elif j <= 69: print(":", end="")
            elif j <= 71: print(".", end="")
            elif j <= 73: print("=", end="")
            elif j <= 75: print("+", end="")
            elif j == 76: print("-", end="")
            elif j == 77: print(":", end="")
            else: print("%", end="")

        # ========= LINE 2 =========
        elif i == 1:
            if j <= 6: print("*", end="")
            elif j <= 10: print("#", end="")
            elif j == 11: print("%", end="")
            elif j <= 13: print("@", end="")
            elif j == 14: print("%", end="")
            elif j <= 18: print("*", end="")
            elif j <= 21: print("=", end="")
            elif j <= 24: print("-", end="")
            elif j <= 26: print(":", end="")
            elif j <= 28: print(".", end="")
            elif j <= 30: print(":", end="")
            elif j <= 32: print("-", end="")
            elif j == 33: print("=", end="")
            elif j == 34: print("+", end="")
            elif j == 35: print("*", end="")
            elif j == 36: print("#", end="")
            elif j <= 41: print("%", end="")
            elif j == 42: print("=", end="")
            elif j == 43: print(":", end="")
            elif j <= 45: print(".", end="")
            elif j == 46: print(":", end="")
            elif j == 47: print("#", end="")
            elif j <= 49: print("@", end="")
            elif j <= 51: print("%", end="")
            elif j == 52: print("@", end="")
            elif j == 53: print("#", end="")
            elif j <= 55: print("-", end="")
            elif j == 56: print(":", end="")
            elif j == 57: print("+", end="")
            elif j <= 59: print("%", end="")
            elif j <= 61: print("#", end="")
            elif j <= 63: print("%", end="")
            elif j == 64: print("@", end="")
            elif j <= 66: print("#", end="")
            elif j <= 68: print("+", end="")
            elif j <= 70: print("=", end="")
            elif j <= 72: print(":", end="")
            elif j <= 75: print(".", end="")
            elif j <= 78: print("=", end="")
            elif j == 79: print("+", end="")
            elif j == 80: print("=", end="")
            elif j == 81: print(":", end="")
            elif j == 82: print(".", end="")
            elif j == 83: print("-", end="")
            else: print("%", end="")

        # ========= LINE 3 =========
        elif i == 2:
            if j <= 6: print("*", end="")
            elif j <= 11: print("#", end="")
            elif j <= 14: print("%", end="")
            elif j == 15: print("#", end="")
            elif j == 16: print("%", end="")
            elif j == 17: print("%", end="")
            elif j == 18: print("+", end="")
            elif j <= 22: print("-", end="")
            elif j <= 29: print(":", end="")
            elif j == 30: print("-", end="")
            elif j == 31: print("+", end="")
            elif j <= 35: print("%", end="")
            elif j <= 37: print("@", end="")
            elif j == 38: print("+", end="")
            elif j <= 41: print(".", end="")
            elif j == 42: print(":", end="")
            elif j == 43: print("+", end="")
            elif j <= 45: print("%", end="")
            elif j <= 47: print("@", end="")
            elif j == 48: print("%", end="")
            elif j == 49: print("*", end="")
            elif j <= 51: print("-", end="")
            elif j == 52: print(":", end="")
            elif j == 53: print("=", end="")
            elif j == 54: print("+", end="")
            elif j <= 56: print("*", end="")
            elif j <= 60: print("#", end="")
            elif j <= 62: print("+", end="")
            elif j == 63: print("=", end="")
            elif j == 64: print("-", end="")
            elif j <= 66: print(":", end="")
            elif j <= 68: print("-", end="")
            elif j <= 70: print("+", end="")
            elif j <= 73: print("=", end="")
            elif j <= 76: print("*", end="")
            else: print("%", end="")

        # ========= LINE 4 =========
        elif i == 3:
            if j <= 7: print("*", end="")
            elif j <= 11: print("#", end="")
            elif j <= 17: print("%", end="")
            elif j == 18: print("#", end="")
            elif j <= 20: print("=", end="")
            elif j <= 26: print("-", end="")
            elif j == 27: print("=", end="")
            elif j == 28: print("+", end="")
            elif j <= 30: print("#", end="")
            elif j <= 32: print("@", end="")
            elif j <= 34: print("%", end="")
            elif j <= 36: print("@", end="")
            elif j == 37: print("%", end="")
            elif j == 38: print("#", end="")
            elif j == 39: print("+", end="")
            elif j == 40: print("-", end="")
            elif j <= 42: print(".", end="")
            elif j == 43: print(":", end="")
            elif j == 44: print("-", end="")
            elif j == 45: print("+", end="")
            elif j <= 49: print("#", end="")
            elif j <= 53: print("*", end="")
            elif j <= 55: print("%", end="")
            elif j == 56: print("#", end="")
            elif j == 57: print("+", end="")
            elif j == 58: print("=", end="")
            elif j == 59: print("-", end="")
            elif j <= 61: print(":", end="")
            elif j <= 65: print(".", end="")
            elif j <= 67: print("-", end="")
            elif j <= 69: print("=", end="")
            elif j <= 72: print("+", end="")
            elif j == 73: print("%", end="")
            elif j == 74: print("*", end="")
            else: print("%", end="")

        # ========= LINE 5 =========
        elif i == 4:
            if j <= 6: print("*", end="")
            elif j <= 11: print("#", end="")
            elif j <= 13: print("%", end="")
            elif j <= 16: print("#", end="")
            elif j <= 17: print("*", end="")
            elif j <= 19: print("=", end="")
            elif j <= 22: print("-", end="")
            elif j == 23: print("=", end="")
            elif j == 24: print("+", end="")
            elif j <= 26: print("*", end="")
            elif j <= 28: print("%", end="")
            elif j <= 31: print("#", end="")
            elif j == 32: print("%", end="")
            elif j == 33: print("+", end="")
            elif j == 34: print("*", end="")
            elif j == 35: print("#", end="")
            elif j == 36: print("%", end="")
            elif j == 37: print("#", end="")
            elif j <= 39: print("=", end="")
            elif j == 40: print("-", end="")
            elif j <= 42: print(":", end="")
            elif j <= 44: print("-", end="")
            elif j <= 52: print("*", end="")
            elif j <= 54: print("+", end="")
            elif j <= 56: print("=", end="")
            elif j <= 58: print(":", end="")
            elif j <= 61: print(".", end="")
            elif j <= 64: print(":", end="")
            elif j <= 66: print("-", end="")
            elif j <= 68: print("+", end="")
            elif j <= 70: print("=", end="")
            elif j <= 72: print("+", end="")
            elif j == 73: print("*", end="")
            elif j == 74: print("+", end="")
            elif j == 75: print("-", end="")
            elif j == 76: print(":", end="")
            elif j == 77: print("=", end="")
            elif j == 78: print("*", end="")
            elif j == 79: print("#", end="")
            else: print("%", end="")

    print()
rows = 5
cols = 120

for i in range(rows):
    for j in range(cols):

        # ========= LINE 1 =========
        if i == 0:
            if j <= 3: print("#", end="")
            elif j <= 6: print("*", end="")
            elif j <= 13: print("#", end="")
            elif j <= 15: print("%", end="")
            elif j == 16: print("*", end="")
            elif j == 17: print("#", end="")
            elif j == 18: print("+", end="")
            elif j == 19: print("=", end="")
            elif j <= 22: print("-", end="")
            elif j <= 24: print("=", end="")
            elif j == 25: print("+", end="")
            elif j <= 27: print("%", end="")
            elif j == 28: print("*", end="")
            elif j == 29: print("=", end="")
            elif j == 30: print("-", end="")
            elif j == 31: print("=", end="")
            elif j == 32: print("+", end="")
            elif j == 33: print("*", end="")
            elif j <= 36: print("#", end="")
            elif j <= 38: print("%", end="")
            elif j == 39: print("+", end="")
            elif j == 40: print("=", end="")
            elif j == 41: print("-", end="")
            elif j == 42: print(":", end="")
            elif j <= 45: print(".", end="")
            elif j <= 47: print(":", end="")
            elif j <= 49: print("-", end="")
            elif j == 50: print("=", end="")
            elif j <= 52: print("+", end="")
            elif j == 53: print("=", end="")
            elif j <= 55: print("-", end="")
            elif j <= 57: print(":", end="")
            elif j <= 64: print(".", end="")
            elif j <= 67: print(":", end="")
            elif j <= 69: print("-", end="")
            elif j == 70: print(":", end="")
            elif j <= 73: print("=", end="")
            elif j == 74: print(":", end="")
            elif j <= 75: print("*", end="")
            elif j <= 77: print("+", end="")
            elif j <= 79: print("=", end="")
            elif j == 80: print("+", end="")
            elif j <= 85: print("%", end="")
            elif j <= 88: print("@", end="")
            elif j <= 96: print("%", end="")
            else: print("#", end="")

        # ========= LINE 2 =========
        elif i == 1:
            if j <= 17: print("#", end="")
            elif j <= 22: print("=", end="")
            elif j == 23: print("-", end="")
            elif j == 24: print("=", end="")
            elif j == 25: print("#", end="")
            elif j == 26: print("%", end="")
            elif j == 27: print("+", end="")
            elif j == 28: print("=", end="")
            elif j <= 30: print("+", end="")
            elif j <= 32: print("*", end="")
            elif j <= 36: print("%", end="")
            elif j <= 38: print("#", end="")
            elif j <= 40: print("+", end="")
            elif j <= 42: print("-", end="")
            elif j <= 44: print("=", end="")
            elif j <= 46: print("-", end="")
            elif j == 47: print(":", end="")
            elif j <= 50: print(".", end="")
            elif j <= 52: print(":", end="")
            elif j <= 56: print("-", end="")
            elif j <= 67: print("-", end="")
            elif j == 68: print("=", end="")
            elif j <= 70: print("-", end="")
            elif j <= 72: print(":", end="")
            elif j == 73: print("*", end="")
            elif j <= 75: print("@", end="")
            elif j == 76: print("#", end="")
            elif j <= 78: print("=", end="")
            elif j == 79: print("-", end="")
            elif j == 80: print("#", end="")
            elif j <= 82: print("%", end="")
            elif j <= 90: print("@", end="")
            else: print("%", end="")

        # ========= LINE 3 =========
        elif i == 2:
            if j <= 13: print("#", end="")
            elif j <= 15: print("*", end="")
            elif j == 16: print("#", end="")
            elif j == 17: print("*", end="")
            elif j <= 22: print("=", end="")
            elif j == 23: print("+", end="")
            elif j <= 34: print("=", end="")
            elif j <= 36: print("-", end="")
            elif j <= 38: print(":", end="")
            elif j <= 40: print(".", end="")
            elif j <= 42: print(":", end="")
            elif j <= 44: print("=", end="")
            elif j <= 48: print("-", end="")
            elif j <= 50: print("+", end="")
            elif j <= 52: print("*", end="")
            elif j == 53: print("+", end="")
            elif j <= 57: print(":", end="")
            elif j <= 59: print("-", end="")
            elif j <= 61: print("=", end="")
            elif j <= 64: print("+", end="")
            elif j <= 67: print("=", end="")
            elif j <= 71: print("-", end="")
            elif j <= 73: print(":", end="")
            elif j == 74: print(".", end="")
            elif j <= 76: print("=", end="")
            elif j <= 78: print("%", end="")
            elif j <= 80: print("@", end="")
            elif j == 81: print("#", end="")
            elif j == 82: print("-", end="")
            elif j == 83: print("*", end="")
            elif j <= 85: print("%", end="")
            elif j <= 93: print("@", end="")
            else: print("%", end="")

        # ========= LINE 4 =========
        elif i == 3:
            if j <= 12: print("#", end="")
            elif j <= 14: print("+", end="")
            elif j <= 16: print("=", end="")
            elif j <= 18: print("*", end="")
            elif j <= 21: print("-", end="")
            elif j <= 27: print(":", end="")
            elif j <= 29: print(".", end="")
            elif j <= 31: print(":", end="")
            elif j <= 33: print(".", end="")
            elif j <= 35: print(":", end="")
            elif j <= 38: print("-", end="")
            elif j <= 40: print("=", end="")
            elif j <= 42: print("+", end="")
            elif j <= 44: print("*", end="")
            elif j == 45: print("#", end="")
            elif j == 46: print("%", end="")
            elif j <= 48: print("@", end="")
            elif j <= 51: print("%", end="")
            elif j <= 53: print("#", end="")
            elif j <= 55: print("*", end="")
            elif j <= 57: print("+", end="")
            elif j <= 59: print("=", end="")
            elif j <= 62: print("-", end="")
            elif j <= 64: print(":", end="")
            elif j == 65: print("+", end="")
            elif j <= 67: print("%", end="")
            elif j <= 69: print("*", end="")
            elif j == 70: print("-", end="")
            elif j == 71: print("+", end="")
            elif j <= 80: print("%", end="")
            else: print("#", end="")

        # ========= LINE 5 =========
        elif i == 4:
            if j <= 11: print("#", end="")
            elif j <= 13: print("*", end="")
            elif j <= 15: print("-", end="")
            elif j == 16: print("=", end="")
            elif j == 17: print("*", end="")
            elif j == 18: print("#", end="")
            elif j == 19: print("+", end="")
            elif j <= 21: print("-", end="")
            elif j <= 26: print(":", end="")
            elif j <= 37: print(".", end="")
            elif j == 38: print(":", end="")
            elif j == 39: print("-", end="")
            elif j == 40: print("=", end="")
            elif j <= 43: print("*", end="")
            elif j <= 45: print("#", end="")
            elif j <= 47: print("@", end="")
            elif j <= 55: print("%", end="")
            elif j <= 59: print("#", end="")
            elif j <= 61: print("*", end="")
            elif j <= 63: print("=", end="")
            elif j <= 65: print("-", end="")
            elif j <= 68: print(":", end="")
            elif j <= 72: print(".", end="")
            elif j <= 74: print(":", end="")
            elif j <= 76: print("-", end="")
            elif j <= 78: print("=", end="")
            elif j <= 80: print("+", end="")
            elif j == 81: print("%", end="")
            elif j == 82: print("@", end="")
            elif j == 83: print("@", end="")
            elif j <= 90: print("%", end="")
            else: print("#", end="")

    print()
rows = 5
cols = 115

for i in range(rows):
    for j in range(cols):

        # ========= LINE 1 =========
        if i == 0:
            if j == 0: print("#", end="")
            elif j <= 3: print("%", end="")
            elif j <= 11: print("#", end="")
            elif j == 12: print("*", end="")
            elif j == 13: print("+", end="")
            elif j == 14: print("#", end="")
            elif j <= 16: print("+", end="")
            elif j <= 18: print("-", end="")
            elif j == 19: print("=", end="")
            elif j == 20: print("*", end="")
            elif j == 21: print("+", end="")
            elif j <= 23: print("-", end="")
            elif j == 24: print("=", end="")
            elif j <= 26: print("-", end="")
            elif j <= 29: print(":", end="")
            elif j <= 33: print(".", end="")
            elif j <= 35: print(":", end="")
            elif j <= 37: print(".", end="")
            elif j <= 40: print(":", end="")
            elif j == 41: print("-", end="")
            elif j == 42: print("=", end="")
            elif j == 43: print("#", end="")
            elif j <= 45: print("@", end="")
            elif j == 46: print("#", end="")
            elif j == 47: print("*", end="")
            elif j == 48: print("%", end="")
            elif j <= 52: print("@", end="")
            elif j == 53: print("%", end="")
            elif j == 54: print("*", end="")
            elif j <= 59: print("+", end="")
            elif j <= 63: print("=", end="")
            elif j <= 65: print("+", end="")
            elif j <= 70: print("*", end="")
            elif j <= 72: print("+", end="")
            elif j <= 74: print("=", end="")
            elif j <= 76: print("-", end="")
            elif j <= 79: print(":", end="")
            elif j <= 81: print("=", end="")
            elif j == 82: print(".", end="")
            elif j == 83: print("+", end="")
            elif j == 84: print("=", end="")
            elif j == 85: print("+", end="")
            elif j <= 93: print("@", end="")
            elif j <= 100: print("%", end="")
            else: print("#", end="")

        # ========= LINE 2 =========
        elif i == 1:
            if j <= 3: print("%", end="")
            elif j <= 11: print("#", end="")
            elif j == 12: print("+", end="")
            elif j == 13: print("*", end="")
            elif j == 14: print("=", end="")
            elif j == 15: print("-", end="")
            elif j == 16: print(":", end="")
            elif j == 17: print("-", end="")
            elif j == 18: print("=", end="")
            elif j == 19: print("*", end="")
            elif j == 20: print("+", end="")
            elif j <= 23: print("=", end="")
            elif j <= 25: print("-", end="")
            elif j <= 33: print(":", end="")
            elif j == 34: print("-", end="")
            elif j == 35: print(":", end="")
            elif j == 36: print("-", end="")
            elif j == 37: print("*", end="")
            elif j == 38: print("%", end="")
            elif j == 39: print("#", end="")
            elif j == 40: print("+", end="")
            elif j == 41: print("=", end="")
            elif j == 42: print("*", end="")
            elif j == 43: print("#", end="")
            elif j <= 49: print("+", end="")
            elif j <= 52: print("=", end="")
            elif j <= 56: print("-", end="")
            elif j <= 60: print("=", end="")
            elif j <= 62: print("+", end="")
            elif j <= 67: print("*", end="")
            elif j <= 69: print("+", end="")
            elif j <= 72: print("=", end="")
            elif j <= 74: print("-", end="")
            elif j <= 76: print(":", end="")
            elif j == 77: print(".", end="")
            elif j == 78: print("-", end="")
            elif j == 79: print("=", end="")
            elif j <= 88: print("@", end="")
            else: print("%", end="")

        # ========= LINE 3 =========
        elif i == 2:
            if j <= 4: print("%", end="")
            elif j <= 12: print("#", end="")
            elif j == 13: print("+", end="")
            elif j == 14: print("=", end="")
            elif j <= 16: print("-", end="")
            elif j <= 18: print(".", end="")
            elif j == 19: print(":", end="")
            elif j <= 24: print("+", end="")
            elif j <= 27: print("=", end="")
            elif j <= 29: print("-", end="")
            elif j <= 34: print(":", end="")
            elif j <= 38: print("-", end="")
            elif j <= 40: print("=", end="")
            elif j <= 42: print("+", end="")
            elif j <= 46: print(":", end="")
            elif j <= 50: print("-", end="")
            elif j <= 54: print("=", end="")
            elif j <= 58: print("+", end="")
            elif j <= 60: print("*", end="")
            elif j <= 64: print("#", end="")
            elif j == 65: print("*", end="")
            elif j <= 67: print("+", end="")
            elif j <= 70: print("=", end="")
            elif j <= 73: print("-", end="")
            elif j <= 75: print(":", end="")
            elif j <= 77: print(".", end="")
            elif j == 78: print(":", end="")
            elif j <= 87: print("@", end="")
            else: print("%", end="")

        # ========= LINE 4 =========
        elif i == 3:
            if j <= 3: print("%", end="")
            elif j <= 12: print("#", end="")
            elif j == 13: print("*", end="")
            elif j <= 15: print("=", end="")
            elif j <= 17: print(":", end="")
            elif j == 18: print("+", end="")
            elif j == 19: print("#", end="")
            elif j <= 25: print("*", end="")
            elif j <= 31: print("+", end="")
            elif j <= 34: print("=", end="")
            elif j <= 38: print("-", end="")
            elif j <= 41: print(":", end="")
            elif j <= 47: print(".", end="")
            elif j <= 49: print(":", end="")
            elif j <= 53: print(".", end="")
            elif j <= 55: print(":", end="")
            elif j <= 58: print("-", end="")
            elif j <= 60: print("=", end="")
            elif j == 61: print("+", end="")
            elif j <= 64: print("*", end="")
            elif j <= 67: print("#", end="")
            elif j <= 69: print("+", end="")
            elif j <= 71: print("*", end="")
            elif j <= 74: print("#", end="")
            elif j <= 76: print("+", end="")
            elif j <= 78: print("=", end="")
            elif j <= 80: print("+", end="")
            elif j <= 82: print("=", end="")
            elif j <= 84: print("-", end="")
            elif j == 85: print("=", end="")
            elif j <= 87: print("#", end="")
            elif j <= 90: print("%", end="")
            else: print("@", end="")

        # ========= LINE 5 =========
        elif i == 4:
            if j <= 4: print("%", end="")
            elif j <= 12: print("#", end="")
            elif j == 13: print("*", end="")
            elif j == 14: print("-", end="")
            elif j == 15: print("=", end="")
            elif j == 16: print(":", end="")
            elif j == 17: print("-", end="")
            elif j == 18: print("+", end="")
            elif j == 19: print("#", end="")
            elif j <= 23: print("*", end="")
            elif j <= 27: print("+", end="")
            elif j <= 30: print("=", end="")
            elif j <= 34: print("-", end="")
            elif j <= 39: print(":", end="")
            elif j <= 43: print(".", end="")
            elif j <= 47: print(":", end="")
            elif j == 48: print("=", end="")
            elif j == 49: print("+", end="")
            elif j <= 52: print("#", end="")
            elif j <= 58: print("%", end="")
            elif j == 59: print("@", end="")
            elif j == 60: print("#", end="")
            elif j <= 62: print("+", end="")
            elif j <= 64: print("=", end="")
            elif j <= 68: print("+", end="")
            elif j <= 71: print("*", end="")
            elif j <= 73: print("+", end="")
            elif j == 74: print("=", end="")
            elif j == 75: print("-", end="")
            elif j <= 78: print(":", end="")
            elif j <= 82: print(".", end="")
            elif j <= 84: print(":", end="")
            elif j <= 86: print("-", end="")
            elif j <= 88: print("=", end="")
            elif j == 89: print("+", end="")
            else: print("%", end="")

    print()
rows = 5
cols = 115

for i in range(rows):
    for j in range(cols):

        # ========= LINE 1 =========
        if i == 0:
            if j == 0: print("#", end="")
            elif j <= 4: print("%", end="")
            elif j <= 15: print("#", end="")
            elif j == 16: print("+", end="")
            elif j == 17: print("-", end="")
            elif j == 18: print(":", end="")
            elif j == 19: print(".", end="")
            elif j == 20: print(":", end="")
            elif j <= 22: print("=", end="")
            elif j <= 29: print("-", end="")
            elif j <= 34: print(":", end="")
            elif j == 35: print("-", end="")
            elif j == 36: print("*", end="")
            elif j == 37: print("#", end="")
            elif j == 38: print("+", end="")
            elif j == 39: print("-", end="")
            elif j <= 42: print(":", end="")
            elif j <= 44: print("-", end="")
            elif j == 45: print("=", end="")
            elif j == 46: print("+", end="")
            elif j <= 48: print("*", end="")
            elif j <= 51: print("#", end="")
            elif j <= 54: print("%", end="")
            elif j <= 56: print("#", end="")
            elif j <= 61: print("*", end="")
            elif j <= 62: print("#", end="")
            elif j <= 70: print("%", end="")
            elif j <= 71: print("#", end="")
            elif j <= 73: print("%", end="")
            elif j <= 75: print("#", end="")
            elif j <= 76: print("-", end="")
            elif j == 77: print(".", end="")
            elif j == 78: print("=", end="")
            elif j <= 89: print("*", end="")
            else: print("#", end="")

        # ========= LINE 2 =========
        elif i == 1:
            if j <= 4: print("#", end="")
            elif j <= 13: print("*", end="")
            elif j <= 17: print("#", end="")
            elif j == 18: print("*", end="")
            elif j == 19: print("+", end="")
            elif j <= 21: print(":", end="")
            elif j <= 24: print("=", end="")
            elif j <= 32: print("-", end="")
            elif j <= 35: print(":", end="")
            elif j <= 38: print("-", end="")
            elif j <= 40: print(".", end="")
            elif j <= 43: print(":", end="")
            elif j <= 45: print("-", end="")
            elif j == 46: print("=", end="")
            elif j == 47: print("+", end="")
            elif j <= 49: print("*", end="")
            elif j <= 52: print("#", end="")
            elif j <= 55: print("%", end="")
            elif j <= 57: print("#", end="")
            elif j <= 59: print("*", end="")
            elif j <= 61: print("+", end="")
            elif j <= 65: print("=", end="")
            elif j <= 67: print("+", end="")
            elif j <= 69: print("*", end="")
            elif j <= 72: print("#", end="")
            elif j <= 77: print("%", end="")
            elif j <= 78: print("@", end="")
            elif j <= 85: print("%", end="")
            elif j <= 87: print("+", end="")
            elif j <= 88: print("-", end="")
            elif j == 89: print(":", end="")
            else: print("*", end="")

        # ========= LINE 3 =========
        elif i == 2:
            if j == 0: print("#", end="")
            elif j <= 4: print("*", end="")
            elif j <= 12: print("+", end="")
            elif j <= 14: print("*", end="")
            elif j <= 19: print("#", end="")
            elif j <= 25: print("*", end="")
            elif j <= 31: print("=", end="")
            elif j <= 41: print("-", end="")
            elif j <= 46: print(":", end="")
            elif j <= 49: print("-", end="")
            elif j <= 53: print("=", end="")
            elif j <= 60: print("-", end="")
            elif j <= 62: print("=", end="")
            elif j <= 65: print("+", end="")
            elif j <= 68: print("*", end="")
            elif j <= 71: print("#", end="")
            elif j <= 79: print("%", end="")
            elif j == 80: print("#", end="")
            elif j <= 82: print(":", end="")
            elif j <= 84: print("=", end="")
            elif j == 85: print(":", end="")
            elif j == 86: print("*", end="")
            elif j <= 89: print("#", end="")
            elif j <= 91: print("%", end="")
            else: print("#", end="")

        # ========= LINE 4 =========
        elif i == 3:
            if j <= 1: print("*", end="")
            elif j <= 3: print("+", end="")
            elif j <= 7: print("=", end="")
            elif j <= 11: print("-", end="")
            elif j <= 13: print("=", end="")
            elif j <= 15: print("+", end="")
            elif j <= 18: print("*", end="")
            elif j <= 21: print("#", end="")
            elif j <= 23: print("*", end="")
            elif j <= 28: print("=", end="")
            elif j <= 32: print("-", end="")
            elif j <= 34: print("=", end="")
            elif j <= 36: print("-", end="")
            elif j <= 44: print(":", end="")
            elif j <= 50: print("-", end="")
            elif j <= 52: print("=", end="")
            elif j <= 54: print("+", end="")
            elif j <= 57: print("*", end="")
            elif j <= 60: print("#", end="")
            elif j <= 68: print("%", end="")
            elif j <= 73: print("@", end="")
            elif j <= 78: print("%", end="")
            elif j <= 80: print("*", end="")
            elif j <= 82: print("-", end="")
            elif j <= 84: print(":", end="")
            elif j <= 86: print("=", end="")
            elif j == 87: print(":", end="")
            elif j == 88: print("*", end="")
            else: print("#", end="")

        # ========= LINE 5 =========
        elif i == 4:
            if j == 0: print("+", end="")
            elif j <= 2: print("=", end="")
            elif j <= 5: print("-", end="")
            elif j <= 9: print(":", end="")
            elif j <= 11: print("-", end="")
            elif j <= 13: print("=", end="")
            elif j <= 15: print("+", end="")
            elif j <= 17: print("*", end="")
            elif j <= 20: print("#", end="")
            elif j <= 23: print("*", end="")
            elif j <= 26: print("+", end="")
            elif j <= 34: print("=", end="")
            elif j <= 36: print("+", end="")
            elif j <= 38: print("=", end="")
            elif j <= 40: print ("-", end="")
            elif j <= 45: print(":", end="")
            elif j <= 48: print("-", end="")
            elif j <= 53: print("=", end="")
            elif j <= 55: print("+", end="")
            elif j <= 58: print("*", end="")
            elif j <= 61: print("#", end="")
            elif j <= 69: print("%", end="")
            elif j == 70: print("#", end="")
            elif j == 71: print("*", end="")
            elif j == 72: print("+", end="")
            elif j <= 75: print("=", end="")
            elif j == 76: print(".", end="")
            elif j <= 78: print("+", end="")
            elif j <= 80: print("+", end="")
            elif j <= 82: print("-", end="")
            elif j <= 84: print(":", end="")
            elif j <= 86: print("-", end="")
            elif j == 87: print("+", end="")
            else: print("#", end="")

    print()
rows = 5
cols = 110

for i in range(rows):
    for j in range(cols):

        # ========= LINE 1 =========
        if i == 0:
            if j <= 2: print("-", end="")
            elif j <= 9: print(":", end="")
            elif j <= 11: print("-", end="")
            elif j == 12: print("=", end="")
            elif j == 13: print("+", end="")
            elif j <= 15: print("*", end="")
            elif j <= 19: print("#", end="")
            elif j <= 22: print("*", end="")
            elif j <= 30: print("+", end="")
            elif j == 31: print("=", end="")
            elif j <= 36: print("+", end="")
            elif j <= 39: print("=", end="")
            elif j <= 41: print("-", end="")
            elif j <= 46: print(":", end="")
            elif j == 47: print("-", end="")
            elif j <= 52: print("+", end="")
            elif j <= 55: print("*", end="")
            elif j <= 60: print("#", end="")
            elif j <= 70: print("%", end="")
            elif j == 71: print("#", end="")
            elif j <= 74: print("*", end="")
            elif j == 75: print(":", end="")
            elif j == 76: print("-", end="")
            elif j == 77: print("*", end="")
            elif j == 78: print("+", end="")
            elif j <= 81: print("=", end="")
            elif j <= 83: print("-", end="")
            elif j <= 85: print(":", end="")
            elif j == 86: print("-", end="")
            elif j == 87: print("+", end="")
            elif j <= 92: print("%", end="")
            else: print("#", end="")

        # ========= LINE 2 =========
        elif i == 1:
            if j <= 10: print(":", end="")
            elif j <= 12: print("-", end="")
            elif j <= 14: print("=", end="")
            elif j <= 16: print("+", end="")
            elif j <= 18: print("*", end="")
            elif j <= 22: print("#", end="")
            elif j <= 30: print("*", end="")
            elif j <= 40: print("+", end="")
            elif j <= 43: print("=", end="")
            elif j <= 48: print("-", end="")
            elif j <= 50: print("=", end="")
            elif j <= 52: print("+", end="")
            elif j <= 56: print("*", end="")
            elif j <= 58: print("#", end="")
            elif j <= 76: print("%", end="")
            elif j <= 78: print("#", end="")
            elif j == 79: print("-", end="")
            elif j == 80: print(".", end="")
            elif j <= 83: print("*", end="")
            elif j <= 91: print("+", end="")
            elif j == 92: print("=", end="")
            elif j <= 94: print("-", end="")
            elif j <= 96: print(":", end="")
            elif j <= 99: print("=", end="")
            elif j == 100: print("+", end="")
            elif j <= 102: print("%", end="")
            else: print("#", end="")

        # ========= LINE 3 =========
        elif i == 2:
            if j == 0: print(":", end="")
            elif j <= 3: print("-", end="")
            elif j <= 7: print(":", end="")
            elif j <= 10: print("-", end="")
            elif j <= 12: print("=", end="")
            elif j <= 14: print("+", end="")
            elif j <= 16: print("*", end="")
            elif j <= 21: print("#", end="")
            elif j <= 27: print("*", end="")
            elif j <= 30: print("#", end="")
            elif j <= 37: print("*", end="")
            elif j <= 38: print("+", end="")
            elif j <= 42: print("=", end="")
            elif j <= 45: print("+", end="")
            elif j <= 47: print("*", end="")
            elif j <= 50: print("#", end="")
            elif j <= 72: print("%", end="")
            elif j == 73: print("#", end="")
            elif j == 74: print("-", end="")
            elif j == 75: print(".", end="")
            elif j == 76: print("+", end="")
            elif j <= 78: print("#", end="")
            elif j <= 87: print("*", end="")
            elif j <= 90: print("+", end="")
            elif j == 91: print("=", end="")
            elif j <= 93: print("-", end="")
            elif j <= 95: print(":", end="")
            elif j <= 98: print("=", end="")
            else: print("+", end="")

        # ========= LINE 4 =========
        elif i == 3:
            if j <= 8: print("-", end="")
            elif j <= 10: print("=", end="")
            elif j <= 13: print("+", end="")
            elif j <= 17: print("*", end="")
            elif j <= 19: print("#", end="")
            elif j <= 23: print("*", end="")
            elif j <= 29: print("#", end="")
            elif j <= 41: print("*", end="")
            elif j <= 45: print("+", end="")
            elif j <= 49: print("*", end="")
            elif j <= 53: print("#", end="")
            elif j <= 76: print("%", end="")
            elif j <= 78: print("#", end="")
            elif j == 79: print(":", end="")
            elif j == 80: print(" ", end="")
            elif j == 81: print("+", end="")
            elif j <= 91: print("%", end="")
            elif j <= 98: print("#", end="")
            elif j <= 102: print("*", end="")
            elif j <= 105: print("+", end="")
            elif j == 106: print("=", end="")
            elif j == 107: print("-", end="")
            elif j <= 109: print(":", end="")
        
        # ========= LINE 5 =========
        elif i == 4:
            if j <= 8: print("=", end="")
            elif j <= 11: print("+", end="")
            elif j <= 25: print("*", end="")
            elif j <= 31: print("#", end="")
            elif j == 32: print("*", end="")
            elif j <= 34: print("+", end="")
            elif j <= 38: print("*", end="")
            elif j <= 40: print("#", end="")
            elif j <= 45: print("*", end="")
            elif j <= 51: print("#", end="")
            elif j <= 53: print("%", end="")
            elif j == 54: print("#", end="")
            elif j <= 74: print("%", end="")
            elif j == 75: print("+", end="")
            elif j == 76: print(".", end="")
            elif j == 77: print(" ", end="")
            elif j == 78: print("=", end="")
            elif j <= 80: print("%", end="")
            elif j <= 88: print("#", end="")
            elif j <= 91: print("*", end="")
            elif j <= 93: print("+", end="")
            elif j == 94: print("=", end="")
            elif j == 95: print("+", end="")
            elif j <= 98: print("-", end="")
            elif j <= 100: print(":", end="")
            elif j == 101: print(".", end="")

    print()
rows = 5
cols = 110

for i in range(rows):
    for j in range(cols):

        # ========= LINE 1 =========
        if i == 0:
            if j <= 2: print("+", end="")
            elif j <= 4: print("*", end="")
            elif j <= 6: print("+", end="")
            elif j <= 18: print("*", end="")
            elif j <= 24: print("+", end="")
            elif j <= 27: print("*", end="")
            elif j <= 33: print("#", end="")
            elif j == 34: print("*", end="")
            elif j <= 39: print("+", end="")
            elif j <= 46: print("*", end="")
            elif j <= 53: print("#", end="")
            elif j <= 71: print("%", end="")
            elif j == 72: print("#", end="")
            elif j == 73: print("-", end="")
            elif j <= 75: print(" ", end="")
            elif j == 76: print("=", end="")
            elif j <= 78: print("%", end="")
            elif j <= 83: print("#", end="")
            elif j <= 89: print("*", end="")
            elif j <= 94: print("+", end="")
            elif j <= 97: print("=", end="")
            elif j == 98: print("-", end="")
            elif j <= 100: print(":", end="")

        # ========= LINE 2 =========
        elif i == 1:
            if j == 0: print("*", end="")
            elif j <= 3: print("#", end="")
            elif j <= 9: print("*", end="")
            elif j <= 14: print("+", end="")
            elif j <= 18: print("=", end="")
            elif j <= 21: print("-", end="")
            elif j <= 23: print("=", end="")
            elif j <= 25: print("+", end="")
            elif j <= 33: print("*", end="")
            elif j <= 43: print("+", end="")
            elif j <= 47: print("*", end="")
            elif j <= 51: print("#", end="")
            elif j <= 69: print("%", end="")
            elif j == 70: print("+", end="")
            elif j == 71: print(".", end="")
            elif j <= 73: print(" ", end="")
            elif j == 74: print("-", end="")
            elif j == 75: print("#", end="")
            elif j <= 77: print("%", end="")
            elif j <= 81: print("#", end="")
            elif j <= 89: print("*", end="")
            elif j <= 92: print("+", end="")
            elif j == 93: print("=", end="")
            elif j <= 95: print("+", end="")
            elif j <= 98: print("=", end="")
            elif j <= 100: print("-", end="")
            else: print(":", end="")

        # ========= LINE 3 =========
        elif i == 2:
            if j <= 6: print("#", end="")
            elif j <= 8: print("*", end="")
            elif j <= 11: print("+", end="")
            elif j <= 14: print("=", end="")
            elif j <= 17: print("-", end="")
            elif j <= 23: print(":", end="")
            elif j <= 25: print("-", end="")
            elif j <= 27: print("=", end="")
            elif j <= 32: print("+", end="")
            elif j == 33: print("=", end="")
            elif j == 34: print("-", end="")
            elif j <= 44: print("+", end="")
            elif j <= 48: print("*", end="")
            elif j <= 51: print("#", end="")
            elif j <= 55: print("%", end="")
            elif j == 56: print("#", end="")
            elif j <= 66: print("%", end="")
            elif j <= 68: print("+", end="")
            elif j == 69: print(":", end="")
            elif j <= 72: print(" ", end="")
            elif j == 73: print("-", end="")
            elif j == 74: print("#", end="")
            elif j <= 76: print("%", end="")
            elif j <= 82: print("#", end="")
            elif j <= 87: print("*", end="")
            elif j <= 90: print("+", end="")
            elif j <= 92: print("=", end="")
            elif j == 93: print("*", end="")
            elif j <= 95: print("=", end="")
            elif j <= 100: print("-", end="")

        # ========= LINE 4 =========
        elif i == 3:
            if j <= 1: print("*", end="")
            elif j <= 4: print("#", end="")
            elif j <= 8: print("*", end="")
            elif j <= 11: print("+", end="")
            elif j <= 13: print("=", end="")
            elif j <= 15: print("-", end="")
            elif j <= 18: print(":", end="")
            elif j <= 25: print(".", end="")
            elif j <= 27: print(":", end="")
            elif j <= 31: print("-", end="")
            elif j <= 35: print("=", end="")
            elif j <= 38: print("-", end="")
            elif j <= 41: print(":", end="")
            elif j <= 53: print("+", end="")
            elif j <= 55: print("*", end="")
            elif j <= 67: print("#", end="")
            elif j <= 71: print("%", end="")
            elif j <= 73: print("+", end="")
            elif j == 74: print(":", end="")
            elif j == 75: print(".", end="")
            elif j <= 78: print(" ", end="")
            elif j == 79: print(".", end="")
            elif j == 80: print("*", end="")
            elif j <= 85: print("%", end="")
            elif j <= 91: print("#", end="")
            elif j <= 98: print("*", end="")
            elif j <= 101: print("+", end="")
            elif j <= 103: print("=", end="")
            elif j == 104: print("*", end="")
            elif j <= 106: print("=", end="")
            else: print("-", end="")

        # ========= LINE 5 =========
        elif i == 4:
            if j <= 1: print("=", end="")
            elif j <= 10: print("+", end="")
            elif j <= 12: print("=", end="")
            elif j <= 15: print("-", end="")
            elif j <= 18: print(":", end="")
            elif j <= 29: print(".", end="")
            elif j <= 31: print(":", end="")
            elif j <= 35: print("-", end="")
            elif j <= 37: print(":", end="")
            elif j <= 41: print(".", end="")
            elif j == 42: print("=", end="")
            elif j <= 53: print("+", end="")
            elif j <= 55: print("*", end="")
            elif j <= 67: print("#", end="")
            elif j == 68: print("+", end="")
            elif j == 69: print(":", end="")
            elif j <= 71: print(" ", end="")
            elif j == 72: print(".", end="")
            elif j <= 74: print(" ", end="")
            elif j == 75: print("+", end="")
            elif j <= 81: print("#", end="")
            elif j <= 88: print("*", end="")
            elif j <= 92: print("+", end="")
            elif j == 93: print("=", end="")
            elif j <= 95: print("-", end="")
            elif j <= 98: print("+", end="")
            elif j <= 100: print("=", end="")
            elif j <= 103: print ("-", end="")
            else: print(":", end="")

    print()
rows = 5
cols = 110

for i in range(rows):
    for j in range(cols):

        # ========= LINE 1 =========
        if i == 0:
            if j <= 3: print(":", end="")
            elif j <= 6: print("-", end="")
            elif j <= 8: print("=", end="")
            elif j == 9: print("+", end="")
            elif j <= 11: print("=", end="")
            elif j <= 13: print("-", end="")
            elif j <= 15: print(":", end="")
            elif j <= 25: print(".", end="")
            elif j <= 28: print(":", end="")
            elif j <= 30: print("-", end="")
            elif j <= 34: print(":", end="")
            elif j <= 38: print(".", end="")
            elif j == 39: print("=", end="")
            elif j <= 48: print("+", end="")
            elif j <= 50: print("*", end="")
            elif j <= 54: print("#", end="")
            elif j <= 59: print("*", end="")
            elif j == 60: print("#", end="")
            elif j == 61: print("*", end="")
            elif j == 62: print("=", end="")
            elif j <= 68: print(" ", end="")
            elif j == 69: print(".", end="")
            elif j == 70: print("=", end="")
            elif j <= 75: print("#", end="")
            elif j <= 80: print("*", end="")
            elif j <= 86: print("+", end="")
            elif j <= 88: print("=", end="")
            elif j == 89: print("-", end="")
            elif j == 90: print("=", end="")
            elif j <= 93: print("+", end="")
            elif j <= 96: print("=", end="")
            elif j <= 98: print("-", end="")
            elif j == 99: print("=", end="")
            elif j == 100: print("-", end="")

        # ========= LINE 2 =========
        elif i == 1:
            if j == 0: print("-", end="")
            elif j <= 2: print(":", end="")
            elif j <= 7: print("-", end="")
            elif j <= 11: print("=", end="")
            elif j <= 14: print("-", end="")
            elif j <= 16: print(":", end="")
            elif j <= 24: print(".", end="")
            elif j <= 26: print(":", end="")
            elif j <= 31: print("-", end="")
            elif j <= 34: print(":", end="")
            elif j <= 38: print(".", end="")
            elif j == 39: print(":", end="")
            elif j == 40: print("-", end="")
            elif j <= 42: print("=", end="")
            elif j <= 48: print("+", end="")
            elif j <= 50: print("*", end="")
            elif j <= 54: print("#", end="")
            elif j <= 56: print("*", end="")
            elif j == 57: print("+", end="")
            elif j <= 59: print("*", end="")
            elif j == 60: print("=", end="")
            elif j <= 68: print(" ", end="")
            elif j == 69: print("-", end="")
            elif j <= 73: print("#", end="")
            elif j <= 81: print("*", end="")
            elif j <= 84: print("+", end="")
            elif j <= 86: print("=", end="")
            elif j <= 88: print("-", end="")
            elif j <= 94: print("=", end="")

        # ========= LINE 3 =========
        elif i == 2:
            if j <= 6: print("-", end="")
            elif j <= 8: print(":", end="")
            elif j <= 17: print("-", end="")
            elif j <= 25: print(":", end="")
            elif j == 26: print("-", end="")
            elif j <= 29: print("=", end="")
            elif j <= 31: print("-", end="")
            elif j <= 35: print(":", end="")
            elif j <= 39: print("-", end="")
            elif j == 40: print(".", end="")
            elif j <= 42: print(":", end="")
            elif j <= 45: print("=", end="")
            elif j <= 49: print("+", end="")
            elif j <= 51: print("*", end="")
            elif j <= 54: print("#", end="")
            elif j <= 58: print("*", end="")
            elif j == 59: print("+", end="")
            elif j == 60: print("-", end="")
            elif j == 61: print(".", end="")
            elif j <= 68: print(" ", end="")
            elif j == 69: print(":", end="")
            elif j <= 74: print("#", end="")
            elif j <= 80: print("*", end="")
            elif j <= 86: print("+", end="")
            elif j <= 88: print("=", end="")
            elif j <= 90: print("-", end="")
            elif j <= 96: print("=", end="")

        # ========= LINE 4 =========
        elif i == 3:
            if j <= 4: print("=", end="")
            elif j <= 9: print("-", end="")
            elif j <= 21: print(":", end="")
            elif j <= 25: print("-", end="")
            elif j <= 28: print("=", end="")
            elif j <= 35: print("-", end="")
            elif j == 36: print("=", end="")
            elif j == 37: print("-", end="")
            elif j <= 39: print("=", end="")
            elif j == 40: print(".", end="")
            elif j <= 42: print(" ", end="")
            elif j == 43: print("-", end="")
            elif j == 44: print("=", end="")
            elif j <= 46: print("+", end="")
            elif j <= 48: print("*", end="")
            elif j <= 51: print("#", end="")
            elif j <= 53: print("*", end="")
            elif j == 54: print("+", end="")
            elif j == 55: print(":", end="")
            elif j <= 63: print(" ", end="")
            elif j == 64: print(".", end="")
            elif j == 65: print("+", end="")
            elif j <= 75: print("*", end="")
            elif j <= 78: print("+", end="")
            elif j <= 86: print("=", end="")
            elif j <= 88: print("-", end="")
            elif j <= 94: print("+", end="")
            elif j <= 98: print("=", end="")

        # ========= LINE 5 =========
        elif i == 4:
            if j <= 6: print("=", end="")
            elif j <= 15: print("-", end="")
            elif j <= 19: print(":", end="")
            elif j <= 22: print("-", end="")
            elif j <= 27: print("=", end="")
            elif j <= 35: print("-", end="")
            elif j <= 37: print("=", end="")
            elif j <= 45: print(" ", end="")
            elif j == 46: print(".", end="")
            elif j == 47: print("-", end="")
            elif j == 48: print("=", end="")
            elif j <= 52: print("+", end="")
            elif j <= 56: print("*", end="")
            elif j <= 58: print("+", end="")
            elif j <= 60: print(":", end="")
            elif j <= 69: print(" ", end="")
            elif j == 70: print("-", end="")
            elif j == 71: print("+", end="")
            elif j <= 75: print("*", end="")
            elif j <= 77: print("+", end="")
            elif j <= 83: print("=", end="")
            elif j <= 86: print("-", end="")
            elif j <= 88: print("+", end="")
            elif j <= 92: print("=", end="")
            elif j <= 95: print("-", end="")

    print()
rows = 5
cols = 110

for i in range(rows):
    for j in range(cols):

        # ========= LINE 1 =========
        if i == 0:
            if j <= 6: print("=", end="")
            elif j <= 18: print("-", end="")
            elif j <= 21: print(":", end="")
            elif j <= 24: print("-", end="")
            elif j <= 28: print("=", end="")
            elif j <= 35: print("+", end="")
            elif j <= 37: print("=", end="")
            elif j <= 39: print("+", end="")
            elif j <= 44: print(" ", end="")
            elif j == 45: print(".", end="")
            elif j <= 47: print("-", end="")
            elif j <= 49: print("=", end="")
            elif j <= 51: print("+", end="")
            elif j == 52: print(":", end="")
            elif j <= 66: print(" ", end="")
            elif j == 67: print(".", end="")
            elif j <= 79: print("+", end="")
            elif j <= 89: print("=", end="")
            elif j <= 91: print("-", end="")
            elif j == 92: print("*", end="")
            elif j <= 94: print("=", end="")
            else: print("-", end="")

        # ========= LINE 2 =========
        elif i == 1:
            if j <= 5: print("=", end="")
            elif j <= 15: print("-", end="")
            elif j <= 18: print(":", end="")
            elif j <= 20: print("-", end="")
            elif j <= 24: print("=", end="")
            elif j <= 37: print("+", end="")
            elif j <= 38: print("*", end="")
            elif j == 39: print(".", end="")
            elif j <= 43: print(" ", end="")
            elif j == 44: print(":", end="")
            elif j == 45: print("+", end="")
            elif j <= 47: print("-", end="")
            elif j <= 49: print(".", end="")
            elif j <= 51: print(":", end="")
            elif j <= 61: print(" ", end="")
            elif j == 62: print("=", end="")
            elif j <= 73: print("+", end="")
            elif j <= 86: print("=", end="")
            elif j == 87: print("+", end="")
            elif j == 88: print("#", end="")
            elif j <= 94: print("=", end="")
            elif j <= 99: print("-", end="")
            elif j == 100: print(":", end="")

        # ========= LINE 3 =========
        elif i == 2:
            if j <= 7: print("=", end="")
            elif j == 8: print("-", end="")
            elif j <= 10: print("=", end="")
            elif j <= 14: print("-", end="")
            elif j <= 16: print(":", end="")
            elif j <= 19: print("-", end="")
            elif j <= 22: print("=", end="")
            elif j <= 38: print("+", end="")
            elif j <= 40: print("*", end="")
            elif j == 41: print("#", end="")
            elif j == 42: print(":", end="")
            elif j <= 46: print(" ", end="")
            elif j == 47: print("*", end="")
            elif j == 48: print("+", end="")
            elif j == 49: print(".", end="")
            elif j <= 51: print(":", end="")
            elif j <= 54: print("-", end="")
            elif j <= 56: print("+", end="")
            elif j <= 58: print("#", end="")
            elif j <= 60: print("*", end="")
            elif j == 61: print(".", end="")
            elif j <= 70: print(" ", end="")
            elif j == 71: print(":", end="")
            elif j <= 79: print("+", end="")
            elif j <= 91: print("=", end="")
            elif j == 92: print("+", end="")
            elif j <= 95: print("*", end="")
            elif j <= 97: print("#", end="")
            elif j <= 100: print("+", end="")
            elif j <= 103: print("=", end="")
            elif j <= 105: print("-", end="")
            elif j <= 108: print(":", end="")

        # ========= LINE 4 =========
        elif i == 3:
            if j <= 8: print("=", end="")
            elif j <= 10: print("-", end="")
            elif j <= 13: print(":", end="")
            elif j <= 17: print("-", end="")
            elif j <= 19: print("=", end="")
            elif j <= 39: print("+", end="")
            elif j <= 41: print("*", end="")
            elif j == 42: print("#", end="")
            elif j == 43: print("%", end="")
            elif j == 44: print("=", end="")
            elif j <= 46: print(" ", end="")
            elif j <= 49: print(".", end="")
            elif j <= 51: print(":", end="")
            elif j <= 53: print("-", end="")
            elif j <= 55: print("+", end="")
            elif j <= 57: print("#", end="")
            elif j <= 59: print("*", end="")
            elif j == 60: print(".", end="")
            elif j <= 69: print(" ", end="")
            elif j == 70: print("=", end="")
            elif j <= 73: print("+", end="")
            elif j == 74: print("=", end="")
            elif j <= 79: print("+", end="")
            elif j == 80: print("=", end="")
            elif j <= 92: print("=", end="")
            elif j == 93: print("+", end="")
            elif j <= 96: print("*", end="")
            elif j <= 98: print("#", end="")
            elif j <= 100: print("+", end="")
            elif j <= 103: print("=", end="")
            elif j <= 105: print("-", end="")
            elif j <= 108: print(":", end="")

        # ========= LINE 5 =========
        elif i == 4:
            if j <= 1: print("-", end="")
            elif j <= 7: print("=", end="")
            elif j <= 9: print("-", end="")
            elif j <= 11: print(":", end="")
            elif j <= 16: print("-", end="")
            elif j <= 18: print("=", end="")
            elif j <= 39: print("+", end="")
            elif j <= 43: print("*", end="")
            elif j == 44: print("#", end="")
            elif j == 45: print("%", end="")
            elif j == 46: print("*", end="")
            elif j <= 49: print(".", end="")
            elif j <= 51: print(":", end="")
            elif j <= 53: print(".", end="")
            elif j <= 55: print("-", end="")
            elif j <= 57: print("+", end="")
            elif j <= 59: print("*", end="")
            elif j <= 63: print("#", end="")
            elif j <= 65: print("+", end="")
            elif j == 66: print(".", end="")
            elif j <= 74: print(" ", end="")
            elif j == 75: print(":", end="")
            elif j <= 78: print("+", end="")
            elif j <= 80: print("=", end="")
            elif j <= 85: print("+", end="")
            elif j <= 93: print("=", end="")
            elif j == 94: print ("+", end="")
            elif j <= 97: print("=", end="")
            elif j <= 100: print ("-", end="")
            elif j <= 103: print (":", end="")

    print()
rows = 4
cols = 110

for i in range(rows):
    for j in range(cols):

        # ========= LINE 1 =========
        if i == 0:
            if j == 0: print("-", end="")
            elif j <= 5: print("=", end="")
            elif j <= 13: print("-", end="")
            elif j <= 16: print("=", end="")
            elif j <= 38: print("+", end="")
            elif j <= 39: print("*", end="")
            elif j <= 41: print("#", end="")
            elif j == 42: print("%", end="")
            elif j == 43: print("*", end="")
            elif j <= 45: print(" ", end="")
            elif j == 46: print(".", end="")
            elif j == 47: print(":", end="")
            elif j <= 49: print(".", end="")
            elif j <= 51: print("=", end="")
            elif j == 52: print("+", end="")
            elif j == 53: print("*", end="")
            elif j <= 55: print("#", end="")
            elif j == 56: print("*", end="")
            elif j == 57: print("-", end="")
            elif j == 58: print(".", end="")
            elif j <= 66: print(" ", end="")
            elif j == 67: print(".", end="")
            elif j == 68: print("=", end="")
            elif j == 69: print("+", end="")
            elif j <= 71: print("=", end="")
            elif j <= 78: print("+", end="")
            elif j <= 82: print("=", end="")
            elif j <= 84: print("+", end="")
            elif j <= 86: print("*", end="")
            elif j == 87: print("%", end="")
            elif j == 88: print("#", end="")
            elif j == 89: print("*", end="")
            elif j == 90: print("+", end="")
            elif j <= 94: print("=", end="")
            elif j <= 98: print("-", end="")
            else: print(":", end="")

        # ========= LINE 2 =========
        elif i == 1:
            if j == 0: print("-", end="")
            elif j <= 4: print("=", end="")
            elif j <= 12: print("-", end="")
            elif j <= 15: print("=", end="")
            elif j <= 25: print("+", end="")
            elif j <= 32: print("=", end="")
            elif j <= 36: print("+", end="")
            elif j <= 38: print("+", end="")
            elif j == 39: print("#", end="")
            elif j <= 41: print("%", end="")
            elif j == 42: print("-", end="")
            elif j <= 44: print(" ", end="")
            elif j == 45: print(".", end="")
            elif j <= 47: print(":", end="")
            elif j == 48: print(":", end="")
            elif j == 49: print("+", end="")
            elif j <= 51: print("*", end="")
            elif j == 52: print("+", end="")
            elif j == 53: print("=", end="")
            elif j == 54: print(".", end="")
            elif j <= 62: print(" ", end="")
            elif j == 63: print(":", end="")
            elif j <= 67: print("=", end="")
            elif j == 68: print("+", end="")
            elif j <= 70: print("=", end="")
            elif j <= 74: print("+", end="")
            elif j <= 78: print("=", end="")
            elif j == 79: print("*", end="")
            elif j == 80: print("%", end="")
            elif j == 81: print("*", end="")
            elif j == 82: print("+", end="")
            elif j <= 88: print("=", end="")
            elif j <= 95: print("-", end="")
            else: print(":", end="")

        # ========= LINE 3 =========
        elif i == 2:
            if j == 0: print("-", end="")
            elif j <= 3: print("=", end="")
            elif j <= 5: print("-", end="")
            elif j <= 12: print("-", end="")
            elif j <= 15: print("=", end="")
            elif j <= 24: print("+", end="")
            elif j <= 33: print("=", end="")
            elif j <= 36: print("+", end="")
            elif j == 37: print("*", end="")
            elif j == 38: print("#", end="")
            elif j == 39: print("%", end="")
            elif j == 40: print("+", end="")
            elif j <= 43: print(" ", end="")
            elif j == 44: print(".", end="")
            elif j == 45: print("-", end="")
            elif j == 46: print("+", end="")
            elif j <= 48: print(":", end="")
            elif j == 49: print(":", end="")
            elif j == 50: print("=", end="")
            elif j == 51: print("#", end="")
            elif j == 52: print("-", end="")
            elif j == 53: print(".", end="")
            elif j <= 61: print(" ", end="")
            elif j == 62: print(".", end="")
            elif j <= 66: print("=", end="")
            elif j <= 69: print("+", end="")
            elif j <= 72: print("=", end="")
            elif j <= 79: print("+", end="")
            elif j <= 81: print("=", end="")
            elif j == 82: print("#", end="")
            elif j == 83: print("*", end="")
            elif j <= 89: print("=", end="")
            elif j <= 95: print("-", end="")
            else: print(":", end="")

        # ========= LINE 4 =========
        elif i == 3:
            if j <= 2: print("=", end="")
            elif j <= 4: print("-", end="")
            elif j == 5: print("=", end="")
            elif j <= 12: print("-", end="")
            elif j <= 22: print("=", end="")
            elif j == 23: print("+", end="")
            elif j <= 35: print("=", end="")
            elif j <= 37: print("+", end="")
            elif j <= 40: print("#", end="")
            elif j == 41: print(":", end="")
            elif j <= 45: print(" ", end="")
            elif j <= 48: print(".", end="")
            elif j == 49: print("-", end="")
            elif j == 50: print("#", end="")
            elif j == 51: print("+", end="")
            elif j <= 53: print(".", end="")
            elif j == 54: print(":", end="")
            elif j <= 62: print(" ", end="")
            elif j == 63: print(":", end="")
            elif j <= 81: print("=", end="")
            elif j == 82: print("+", end="")
            elif j == 83: print("#", end="")
            elif j == 84: print("+", end="")
            elif j <= 88: print("=", end="")
            else: print("-", end="")

    print()

